name: DamageIndicator
main: cl.mastercode.DamageIndicator.DIMain
authors: [ Beelzebu, CristianDossow ]
version: ${project.version}
softdepend: [ ProtocolLib ]
api-version: 1.13
commands:
  damageindicator:
    description: Main DamageIndicator command
    usage: /<command> <arguments>
    aliases: [ di ]
permissions:
  damageindicator.admin:
    description: Access to admin commands
