name: DamageIndicator
main: cl.mastercode.DamageIndicator.Main
author: CristianDossow
authors: [Beelzebu]
version: ${project.version}
commands:
  damageindicator:
    description: Main DamageIndicator command
    usage: /<command> <arguments>
    aliases: [di]
permissions:
  damageindicator.admin:
    description: Access to admin commands