name: DamageIndicator
main: cl.mastercode.DamageIndicator.Main
author: CristianDossow
version: ${project.version}
commands:
  DamageIndicator:
    description: Main DamageIndicator command
    usage: /<command> <arguments>
    aliases: di
permissions:
  damageindicator.admin:
    description: Access to admin commands